### PR TITLE
Implement a LastLogAcitivity check

### LINKED ISSUE #98: Activity check based on parsing last access times from a log file
As a result of [this discussion](https://github.com/languitar/autosuspend/discussions/97), a new activity check would probably help that detects activity by iterating a log file and parsing it for the most recent timestamp based on a regular expression (line by line). Activity should appear if the latest matching line (containing a timestamp) appeared recently within a configurable time interval.

### PR DESCRIPTION
**Pull request by languitar**
Parses a log file and uses that first timestamp found when iterating the
file starting from the last line.

Will fix #98

### CODE REVIEW

**Comment by languitar** [comment]
@niram8 would you mind giving this check a try? This should solve your log file problem without a shell script.

**Comment by niram8** [comment]
> 
> 
> @niram8 would you mind giving this check a try? This should solve your log file problem without a shell script.

I would be happy to test. I do not know how to do it. How can I update my current autosuspend installation to test the new feature? And how should the autosuspend config file look like?

**Comment by languitar** [comment]
> How can I update my current autosuspend installation to test the new feature? And how should the autosuspend config file look like?

You need to install autosuspend from the development source to test this. Ideally, you deinstall the existing package before testing (you should back up your existing config file before doing that). I have updated the from-source installation instructions in the manual to make the installation of the update version more easy for you: https://autosuspend.readthedocs.io/en/latest/installation.html#manual-installation. Use `feature/98-last-log-time-check` as the branch name behind the `@` character in the Git URL.

**Comment by niram8** [comment]
I got the following error while I tried to install the brannch feature/98-last-log-time-check:

root@nextcloud ~]# python3 -m venv /opt/autosuspend /opt/autosuspend/bin/pip install git+https://github.com/languitar/autosuspend.git@feature/98‐last‐log‐time‐check#egg=autosuspend[all]
Error: Unable to create directory '/opt/autosuspend/bin/pip'
[root@nextcloud ~]#

There is already a file "pip" in directory "/opt/autosuspend/bin/" but no directory "pip"

The process is difficult for me as a non-linux user

**Comment by languitar** [comment]
You have to execute the two lines in the instruction in two separate invocations, not a single one.

**Comment by niram8** [comment]
Still errors. Here the output:

[root@nextcloud ~]# python3 -m venv /opt/autosuspend
[root@nextcloud ~]# /opt/autosuspend/bin/pip install git+https://github.com/languitar/autosuspend.git@feature/98‐last‐log‐time‐check#egg=autosuspend[all]
Collecting autosuspend[all] from git+https://github.com/languitar/autosuspend.git@feature/98‐last‐log‐time‐check#egg=autosuspend[all]
  Cloning https://github.com/languitar/autosuspend.git (to revision feature/98‐last‐log‐time‐check) to /tmp/pip-install-9ijj39iv/autosuspend
  Did not find branch or tag 'feature/98‐last‐log‐time‐check', assuming revision or ref.
error: pathspec 'feature/98‐last‐log‐time‐check' did not match any file(s) known to git
Command "git checkout -q feature/98‐last‐log‐time‐check" failed with error code 1 in /tmp/pip-install-9ijj39iv/autosuspend
[root@nextcloud ~]#

A lot of things happen if I use "master" instead of "eature/98‐last‐log‐time‐check"
/opt/autosuspend/bin/pip install git+https://github.com/languitar/autosuspend.git@master#egg=autosuspend[all]
But still a lot of erros. I can past the outpout if appropriate

**Comment by languitar** [comment]
That is very strange. I just copy and pasted your git URL and it doesn't work. When I build the URL on my own it works. Looks like there is some invisible control character inside. Please try this one:

git+https://github.com/languitar/autosuspend.git@feature/98-last-log-time-check#egg=autosuspend[all]

**Comment by niram8** [comment]
Still error:

[root@nextcloud ~]# python3 -m venv /opt/autosuspend
[root@nextcloud ~]# https://github.com/languitar/autosuspend.git@feature/98-last-log-time-check#egg=autosuspend%5Ball%5D
sh: 1: https://github.com/languitar/autosuspend.git@feature/98-last-log-time-check#egg=autosuspend%5Ball%5D: not found
[root@nextcloud ~]# git+https://github.com/languitar/autosuspend.git@feature/98-last-log-time-check#egg=autosuspend[all]
sh: 1: git+https://github.com/languitar/autosuspend.git@feature/98-last-log-time-check#egg=autosuspend[all]: not found
[root@nextcloud ~]#

**Comment by languitar** [comment]
That was only the URL, not the whole command to execute.

```sh
python3 -m venv /opt/autosuspend

/opt/autosuspend/bin/pip install git+https://github.com/languitar/autosuspend.git@feature/98-last-log-time-check#egg=autosuspend[all]
```

That's what you need to execute.

**Comment by niram8** [comment]
Run through. But a lot of error messages in the output , see attached file (hope it works how I attached the file)
Sorry for the inconvenience while testing. My linux skills are really basic and I do not understand what is behind the scene with this command

[autosuspend-2021-02-21_error5.txt](https://github.com/languitar/autosuspend/files/6024971/autosuspend-2021-02-21_error5.txt)

**Comment by languitar** [comment]
Ah, you are missing the python development headers. That prevents a native dependency from compiling. Do the following to install them:

```sh
apt-get install python3-dev build-essential
```

Maybe that's enough to make things work.

**Comment by niram8** [comment]
Apparently not so eay. See attached file.
[autosuspend-2021-02-22_error6.txt](https://github.com/languitar/autosuspend/files/6025030/autosuspend-2021-02-22_error6.txt)

**Comment by languitar** [comment]
> Do you want to continue? [Y/n] Abort.

You didn't complete the package installation but cancelled it.

**Comment by niram8** [comment]
Sorry I forgot the -y parameter (apt-get install python3-dev build-essential) Otherwise it does not work on my system (forwhatever reason)
 But apparently still something is missing. See attached file
[autosuspend-2021-02-22_error7.txt](https://github.com/languitar/autosuspend/files/6025164/autosuspend-2021-02-22_error7.txt)

**Comment by languitar** [comment]
At least yet another missing package for enabling compilation:

```
apt-get install -y pkg-config python3-wheel
```

Maybe afterwards it gets further.

**Comment by niram8** [comment]
Still error. 
[autosuspend-2021-02-24_error8.txt](https://github.com/languitar/autosuspend/files/6039177/autosuspend-2021-02-24_error8.txt)
Apparently still not all packages installed. What do I need totally?

**Comment by languitar** [comment]
I suspect you need to install `dbus-1-dev`

**Comment by niram8** [comment]
Which package should I install? I looked on the web but cannot identify it. Maybe you could give me the complete apt-get install command.

**Comment by languitar** [comment]
```
apt-get install -y dbus-1-dev
```

?

**Comment by niram8** [comment]
This gives the error: Unable to locate package dbus-1-dev

**Comment by languitar** [comment]
I am not sure on what Linux distribution you are running. Maybe the package is called `libdbus-1-dev` on your system.

**Comment by niram8** [comment]
My linux distribution is:  turnkey-nextcloud-16.0-buster-amd64
It should be the latest Debian Buster

But I think I give it up. I cannot manage the manual install 

I further installed:
apt-get install -y libdbus-1-dev
apt-get install -y glib-2.0
apt-get install -y libglib2.0

Still errors (see attached file)
[autosuspend-2021-03-02_error12.txt](https://github.com/languitar/autosuspend/files/6071956/autosuspend-2021-03-02_error12.txt)

**Comment by languitar** [comment]
That's normal. You do not have the development headers for some packages which need to be installed before the autosuspend installation can succeed. The pattern is always the same. In case something is missing the appropriate -dev package needs to be installed. Your suspicion with `libglib2.0` was correct already, but for compilation to succeed, you always need the package version with the `-dev` postfix. So in this case `libglib2.0-dev`

**Comment by languitar** [comment]
I'll just merge this for now. In my test cases this works. If something doesn't work as expected once this is released, please open an new issue.

**Pull request merged**
